// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs79ONH7hsSusHVnkKttvJMjv6G4Iqnvs',
    appId: '1:905779153032:web:1171e08e1f3850dbfbf73d',
    messagingSenderId: '905779153032',
    projectId: 'dominiks-twitter',
    authDomain: 'dominiks-twitter.firebaseapp.com',
    storageBucket: 'dominiks-twitter.appspot.com',
    measurementId: 'G-FY0QZYM5NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEo1lmqgVXVZTSBI6NVjX1NAsl66vfmo',
    appId: '1:905779153032:android:5599fcd71b0d4d62fbf73d',
    messagingSenderId: '905779153032',
    projectId: 'dominiks-twitter',
    storageBucket: 'dominiks-twitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL3dHsD8OO9Gi1c6GgGxijEnOQBb8i8ZQ',
    appId: '1:905779153032:ios:e0a8605e1f9be486fbf73d',
    messagingSenderId: '905779153032',
    projectId: 'dominiks-twitter',
    storageBucket: 'dominiks-twitter.appspot.com',
    iosBundleId: 'com.example.twitterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL3dHsD8OO9Gi1c6GgGxijEnOQBb8i8ZQ',
    appId: '1:905779153032:ios:16f3a7a7d0d1c716fbf73d',
    messagingSenderId: '905779153032',
    projectId: 'dominiks-twitter',
    storageBucket: 'dominiks-twitter.appspot.com',
    iosBundleId: 'com.example.twitterProject.RunnerTests',
  );
}
